name: Package-Debian-Build

on:
  push:
    tags:
    - '*'

  # allow manually starting this workflow
  workflow_dispatch:

jobs:
  industrial_ci:
    name: Noetic
    runs-on: ubuntu-latest
    env:
      CI_NAME: Package-Debian-Build
      OS_NAME: ubuntu
      OS_CODE_NAME: focal
      ROS_DISTRO: noetic
      ROS_REPO: main
      UPSTREAM_WORKSPACE: 'dependencies.rosinstall'
      ROSDEP_SKIP_KEYS: "iwyu ros_industrial_cmake_boilerplate"
      CCACHE_DIR: "/home/runner/work/opw_kinematics/opw_kinematics/Package-Debian-Build/.ccache"
      BEFORE_RUN_TARGET_TEST_EMBED: "ici_with_unset_variables source /root/target_ws/install/setup.bash"
      TARGET_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Release -DOPW_PACKAGE=ON"
      CPACK_ARTIFACTS_DIR: "/root/artifacts"
      CPACK_ARTIFACTS_EXT: "deb"
      CPACK_WORKING_DIR: '/root/target_ws/build/opw_kinematics'
      DOCKER_RUN_OPTS: '-e CPACK_WORKING_DIR -e CPACK_ARTIFACTS_DIR -e CPACK_ARTIFACTS_EXT -v ~/work/opw_kinematics/opw_kinematics/artifacts:/root/artifacts'
      AFTER_SCRIPT: '$target_ws/src/opw_kinematics/.run-cpack'
    steps:
      - uses: actions/checkout@v2
      - name: Create artifacts directory
        run: |
          mkdir artifacts

      - name: Free Disk Space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: ccache cache files
        uses: actions/cache@v1.1.0
        with:
          path: ${{ env.CI_NAME }}/.ccache
          key: ${{ env.CI_NAME }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ env.CI_NAME }}-ccache-

      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{env}}

      - uses: actions/upload-artifact@v2
        with:
          name: debian_package
          path: /home/runner/work/opw_kinematics/opw_kinematics/artifacts/*.deb

      - uses: actions/upload-artifact@v2
        with:
          name: archive_package
          path: /home/runner/work/opw_kinematics/opw_kinematics/artifacts/*.tar.xz
